spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: someClientId
            clientSecret: someClientSecret
logging:
  level:
    ROOT: INFO
    be: TRACE